---
title: "Part I: In Vivo Approach Molar calculation"
author: "Jess Archibald & Mark Mikkelsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libs, include=FALSE}

# Function to install and/or load necessary packages
load.packages <- function(pkg) {
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) {
    install.packages(new.pkg, dependencies = T)
  }
  sapply(pkg, require, character.only = T)
}

# Packages needed for this script
packages <- c(
  "tidyverse",
  "knitr")

load.packages(packages)

```


## Molar concentration equation

$$ 
[M]_{molar} = \frac{S_{M_{obs}} (f_{GM} d_{GM} R_{H2O_{GM}} + 
f_{WM} d_{WM} R_{H2O_{WM}} + 
f_{CSF} d_{CSF} R_{H2O_{CSF}})}
{S_{H2O_{obs}} (1 - f_{CSF_{H2O}}) R_{M_{\text{GM/WM}}}}
[H_2O]_{molar}
$$

## Relaxation correction equation

$$
R = \exp\left(-\frac{T_E}{T_2}\right) \left[ 1 - \exp\left(-\frac{T_R}{T_1}\right) \right]
$$
The ratio intrinsic of GM to WM metabolite concentration is not known, so use the assumption 1.2 (Gasparovic et al., 2018):

$$
R_{M_{\text{GM/WM}}} = \frac{f_{\text{GM}} d_{\text{GM}} \left(\frac{[M_{\text{GM}}]}{[M_{\text{WM}}]}\right) R_{M_{GM}} + f_{\text{WM}} d_{\text{WM}} R_{M_{WM}}}
{f_{\text{GM}} d_{\text{GM}} \left(\frac{[M_{\text{GM}}]}{[M_{\text{WM}}]}\right) + f_{\text{WM}} d_{\text{WM}}}
$$


```{r vals, echo=FALSE, message=FALSE, warning=FALSE}

# Create a data frame with the literature values
literature_values <- as_tibble(data.frame(
  Tissue = c("Gray matter", "White matter", "CSF"),
  T2_ms = c(110, 79.2, 503),
  T1_ms = c(1331, 832, 3817),
  Reference = "Dhamala et al., 2019"
))

# Print table in RMarkdown using kable
knitr::kable(literature_values, 
             caption = "Literature values",
             align = "c")

```

```{r relaxation, message=FALSE, warning=FALSE, include=TRUE}

# Define the acquisition parameters
TE <- 35  # TE in ms
TR <- 2000  # TR converted to ms (2 seconds = 2000 ms)

# Define tissue-specific T2 and T1 values (in ms)
T2_GM <- 110  # T2 for Gray Matter in ms
T1_GM <- 1331 # T1 for Gray Matter in ms

T2_WM <- 79.2  # T2 for White Matter in ms
T1_WM <- 832   # T1 for White Matter in ms

T2_CSF <- 503  # T2 for CSF in ms
T1_CSF <- 3817 # T1 for CSF in ms


# Define the relaxation equation function (using ms units)
relaxation_eq_ms <- function(TE, TR, T2, T1) {
  return(exp(-TE / T2) * (1 - exp(-TR / T1)))
}

# Calculate R for each tissue type
R_GM  <- relaxation_eq_ms(TE, TR, T2_GM, T1_GM)
R_WM  <- relaxation_eq_ms(TE, TR, T2_WM, T1_WM)
R_CSF <- relaxation_eq_ms(TE, TR, T2_CSF, T1_CSF)

# Create a data frame to display the results in a table
results <- data.frame(
  Tissue = c("Gray Matter", "White Matter", "CSF"),
  Value = c(R_GM, R_WM, R_CSF),
  Units = rep("ms", 3)
)

knitr::kable(results, caption = "Relaxation Rates for Different Tissue Types")

# Metabolite relaxation constants
# Wyss et al. (2018) (doi:10.1002/mrm.27067)
T2_M <- list(
  "GM" = data.frame(
    tNAA = mean(c(253, 223)), 
    tCr  = mean(c(148, 134)),
    Glx  = 135,
    Glu  = 135,
    mI   = 244
  ),
  "WM" = data.frame(
    tNAA = mean(c(343, 310)),
    tCr  = mean(c(166, 129)),
    Glx  = 124,
    Glu  = 124,
    mI   = 161
  )
)

# Mlynárik et al. (2001) (doi:10.1002/nbm.713)
T1_M <- list(
  "GM" = data.frame(
    tNAA = 1.47 * 1e3, 
    tCr  = 1.46 * 1e3,
    Glx  = 1.20 * 1e3,
    Glu  = 1.27 * 1e3,
    mI   = mean(c(1.23, 1.19))
  ),
  "WM" = data.frame(
    tNAA = 1.35 * 1e3, 
    tCr  = 1.24 * 1e3,
    Glx  = 0.96 * 1e3,
    Glu  = 1.17 * 1e3,
    mI   = mean(c(1.01, 0.93))
  )
)

```


## Define constants & R values calcualted

```{r constants, echo=TRUE}

# Water density values (Near et al., 2021)
d_GM  <- 0.78
d_WM  <- 0.65
d_CSF <- 0.97

# Calculated with study params
R_H2O_GM  <- 0.5655762
R_H2O_WM  <- 0.5847118
R_H2O_CSF <- 0.3804226

# Metabolic GM:WM ratio (Near et al., 2021)
M_GM_WM_ratio <- 1.20

# Molar concentration of water (in mM)
# H2O_molar <- 0.005501 ..  / 1e4
H2O_molar <- 55.51 * 1e3

```

```{r load}


# data <- read.csv("/path2data/SM_SH2O.csv")

```

```{r spm}

f_GM  <- data$GM_SPM
f_WM  <- data$WM_SPM
f_CSF <- data$CSF_SPM

```

## Compute tissue-weighted relaxation term (R<sub>GM/WM</sub>)

```{r calc}

S_M_obs   <- data$raw.water.scaled.ratio.tNAA / 55556
S_H2O_obs <- 1

# Function to calculate metabolite concentration
calculate_molar_conc <- function(S_M_obs, S_H2O_obs, metab, TE, TR, T2_M, T1_M, f_GM, f_WM, f_CSF, d_GM, d_WM, d_CSF, R_H2O_GM, R_H2O_WM, R_H2O_CSF, R_M_GM, R_W_GM, H2O_molar) {
  R_M_GM <- relaxation_eq_ms(TE, TR, T2_M$GM[[metab]], T1_M$GM[[metab]])
  R_M_WM <- relaxation_eq_ms(TE, TR, T2_M$WM[[metab]], T1_M$WM[[metab]])
  R_M_GM_WM <- (f_GM * d_GM * M_GM_WM_ratio * R_M_GM + f_WM * d_WM * R_M_WM) /
    (f_GM * d_GM * M_GM_WM_ratio + f_WM * d_WM)
  numerator   <- S_M_obs * ((f_GM * d_GM * R_H2O_GM) + (f_WM * d_WM * R_H2O_WM) + (f_CSF * d_CSF * R_H2O_CSF))
  denominator <- S_H2O_obs * (1 - f_CSF) * R_M_GM_WM
  molar_conc  <- (numerator / denominator) * H2O_molar
  return(molar_conc)
}

################ TESTING ONE AT A TIME GROUND
# Calculate metabolite concentration
molar_conc_result <- as_tibble(calculate_molar_conc(S_M_obs, S_H2O_obs, "tNAA", TE, TR, T2_M, T1_M, f_GM, f_WM, f_CSF, d_GM, d_WM, d_CSF, R_H2O_GM, R_H2O_WM, R_H2O_CSF, R_M_GM, R_W_GM, H2O_molar))
colnames(molar_conc_result) <- "tNAA"

# Print result
print(molar_conc_result, n = nrow(molar_conc_result))

```

## Now for all metabolites...

```{r calc II}

# List of metabolites to loop over
# metabolites <- c("tNAA", "tCr", "Glx", "Glu", "mI")
# List of metabolites to loop over
metabolites <- c("tNAA", "tCr", "Glx", "Glu", "mI")

# Loop to calculate molar concentration for each metabolite
molar_data <- as_tibble(data)

for (metabolite in metabolites) {
  # Create the variable names dynamically
  # Sm_col   <- paste0("Sm.", metabolite)
  # Sh2o_col <- paste0("Sh2o.", metabolite)
  Sm_col   <- paste0("raw.water.scaled.ratio.", metabolite)
  Sh2o_col <- 1

  # Calculate molar concentration
  molar_data[[paste0("molar_", metabolite)]] <- calculate_molar_conc(
    # molar_data[[Sm_col]],
    # molar_data[[Sh2o_col]],
    molar_data[[Sm_col]] / 55556,
    Sh2o_col,
    metabolite, TE, TR, T2_M, T1_M,
    f_GM, f_WM, f_CSF, d_GM, d_WM, d_CSF, R_H2O_GM, R_H2O_WM, R_H2O_CSF, R_M_GM, R_W_GM, H2O_molar
  )
}

# Check the result
# print(molar_data)

# Select only the columns with metabolite data (molar concentrations)
molar_columns <- grep("^molar_", names(molar_data), value = TRUE)

# Create a new data frame with just the molar data
molar_allmets_spm <- molar_data[, molar_columns]

# Add column names
colnames(molar_allmets_spm) <- metabolites

# Save it as a CSV file

write.csv(molar_allmets_spm, "~/Desktop/molar_allmets_SPM_MM.csv", row.names = FALSE)

```





